Fix multiarr js
ingRicardo/challenges pull request #11
Opened 2019-05-23 22:51 UTC by ingRicardo

Fix multiarr js

2019-05-25 17:22 UTC, alejandrolechuga requested changes

2019-05-25 17:22 UTC, alejandrolechuga commented on scriptTest.js
> +
Don't use global variables like myData, the function should take an input and give you an output

2019-05-25 17:22 UTC, alejandrolechuga commented on scriptTest.js
> +        if (typeof arr[i] == 'object'){
to check if is an array you can do `Array.isArray(foo)`

2019-05-25 20:29 UTC, ingRicardo commented on scriptTest.js
> +
done

2019-05-25 20:29 UTC, ingRicardo commented on scriptTest.js
> +        if (typeof arr[i] == 'object'){
done

2019-06-06 06:25 UTC, alejandrolechuga commented
close this PR

2019-06-12 04:19 UTC, closed without merging